{"uuid": "5c8e608f-cd71-4dd3-a251-41e1806c21c8", "counter": 5, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None\u001b[0m\r\n\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"changed\": false, \"msg\": \"Could not detect which package manager to use. Try gathering facts or setting the \\\"use\\\" option.\"}\u001b[0m", "start_line": 4, "end_line": 6, "runner_ident": "f05703db-9621-4d1e-a0f0-f514590ee604", "event": "runner_on_failed", "pid": 7664, "created": "2021-06-27T09:59:36.468305", "parent_uuid": "41a329d9-2439-ad53-3d6b-000000000008", "event_data": {"playbook": "/home/st/Desktop/ansi/config/tmp/files/programmed_local19.yml", "playbook_uuid": "e87182fb-d598-4bbc-9566-4d0ce581b211", "play": "19", "play_uuid": "41a329d9-2439-ad53-3d6b-000000000006", "play_pattern": "local", "task": "package", "task_uuid": "41a329d9-2439-ad53-3d6b-000000000008", "task_action": "package", "task_args": "", "task_path": "/home/st/Desktop/ansi/config/tmp/files/programmed_local19.yml:9", "host": "127.0.0.1", "remote_addr": "127.0.0.1", "res": {"msg": "Could not detect which package manager to use. Try gathering facts or setting the \"use\" option.", "exception": "NoneType: None\n", "_ansible_no_log": false, "changed": false}, "start": "2021-06-27T09:59:35.742491", "end": "2021-06-27T09:59:36.468187", "duration": 0.725696, "ignore_errors": null, "event_loop": null, "uuid": "5c8e608f-cd71-4dd3-a251-41e1806c21c8"}}